apiVersion: apps/v1
kind: Deployment
metadata:
  name: all
spec:
  template:
    spec:
      containers:
      - name: all
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi" 