apiVersion: v1
kind: Service
metadata:
  name: mcp
  labels:
    app: backend
    service: mcp
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    name: mcp
  type: ClusterIP 