apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/deployment.yaml
  - frontend/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/mcp-service.yaml
  - backend/configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - databases/mongo-deployment.yaml
  - databases/mongo-service.yaml
  - databases/postgres-deployment.yaml
  - databases/postgres-service.yaml
  - databases/postgres-initdb-configmap.yaml

namespace: agentic-rag

commonLabels:
  app.kubernetes.io/part-of: agentic-rag
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: env-config
    literals:
      - NEXT_PUBLIC_API_URL=http://api.app.local
      - NEXTAUTH_URL=http://app.local

secretGenerator:
  - name: app-secrets
    env: secrets/app.env
  - name: db-secrets
    env: secrets/db.env

patches:
  - path: patches/local-development.yaml
    target:
      kind: Deployment

images:
  - name: frontend
    newName: frontend
    newTag: dev
  - name: backend
    newName: backend
    newTag: dev 